#objects
OBJS= main.o my_string.o

CC= cc 

#compiler flags -g for debug -O3 for optimization
CFLAGS= -g -O3

all: main

%.o: %.c
	${CC} ${CFLAGS} -c -o $@ $<

main: ${OBJS} main.o 
	${CC} -o $@ $^

run: main
	./main

clean:
	rm -f *.o main

my_string.o: my_string.c my_string.h